kls:
	gcc kls.c ../apue/error.c -o kls
ionobuf:
	gcc ionobuf.c ../apue/error.c -o ionobuf
iobuf:
	gcc iobuf.c ../apue/error.c -o iobuf
procctl:
	gcc procctl.c ../apue/error.c -o procctl
clean:
	rm *.exe
