errorfile = ../apue/error.c
all : 1_1_ls 1_2_nobufio 1_3_bufio 1_4_uid_gid 1_5_shell 1_6_error
	
1_1_ls:
	gcc 1_1_ls.c $(errorfile) -o 1_1_ls
1_2_nobufio:
	gcc 1_2_nobufio.c $(errorfile) -o 1_2_nobufio
1_3_bufio:
	gcc 1_3_bufio.c $(errorfile) -o 1_3_bufio
1_4_uid_gid:
	gcc 1_4_uid_gid.c $(errorfile) -o 1_4_uid_gid
1_5_shell:
	gcc 1_5_shell.c $(errorfile) -o 1_5_shell
clean:
	rm *.exe *.o
